yaml
name: Prueba secrets

on: push

jobs:
  comparar:
    runs-on: self-hosted
    env:
      SECRET_DEV: ${{ secrets.DEV_TOKEN }}
    steps:
      - name: Comparar DEV_TOKEN con LOCAL_DEV_TOKEN
        shell: powershell
        run: |
          if ($env:SECRET_DEV -ceq $env:LOCAL_DEV_TOKEN) {
            Write-Host "Los tokens COINCIDEN"
          } else {
            Write-Host "Los tokens NO coinciden"
            exit 1
          }
